sudo: required

services:
   - docker

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install: true

script: docker/vespa-ci.sh

